### ISSUE TITLE
Error in python code 

### ISSUE THREAD

**Issue by YousufAzadSami** [stefanopassador/Tutorial_DockerPythonPostgres#3]
if the code is run via `docker compose up -d`, then in the python container there is a error - 

```
File "/code/app.py", line 19
    "VALUES ("+\ 
                 ^
SyntaxError: unexpected character after line continuation character
```

**Comment by stefanopassador** [comment]
Can you paste the line of codes that are generating the error? It seems a syntax issue.

**Comment by marcelomagario** [comment]
It happened the same error for me. I fix it removing a "space" right after the " ("+\ ".

**Comment by stefanopassador** [comment]
@marcelomagario could you please share the code that is generating that issue? So, I will be able to fix it.
